name: Hybrid Workflow

on:
  workflow_dispatch:

jobs:
  hybrid_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Run command in Ubuntu VM
        run: echo "This is running on the GitHub-hosted VM"

      - name: Run command in Alpine container
        uses: docker://alpine:3.14
        with:
          entrypoint: /bin/sh
          args: -c "echo 'This is running inside Alpine container'; cat /etc/os-release"
